### ISSUE TITLE
Show_bias.py not executing 

### ISSUE THREAD

**Issue by ahtsham58** [THUDM/KBRD#10]
Hey @qibinc 

I am done with all the three training steps. I can see model files and everything in "saved" folder.

Now I want to run last command "show_bias.py" but getting an error.. here is the error description..
could you please me ..?

`[  pytorch_preprocess: False ]
[  pytorch_teacher_batch_sort: False ]
[  pytorch_teacher_dataset: None ]
[  pytorch_teacher_task: None ]
[  shuffle: False ]
[ ParlAI Image Preprocessing Arguments: ]
[  image_cropsize: 224 ]
[  image_size: 256 ]
Traceback (most recent call last):
  File "scripts/show_bias.py", line 41, in <module>
    agent = create_agent(opt, requireModelExists=True)
  File "/root/KBRD/parlai/core/agents.py", line 587, in create_agent
    raise RuntimeError('Need to set `model` argument to use create_agent.')
RuntimeError: Need to set `model` argument to use create_agent.
`

**Comment by ahtsham58** [comment]
please can you help..

**Comment by ahtsham58** [comment]
Hi,
can you please lead how i can generate dialogue conversations using this KBRD system. My model is already trained..

**Comment by qibinc** [comment]
Hi @ahtsham58 ,

You can run the following command to generate conversations on the test set.

```bash
python scripts/display_model.py -t redial -mf saved/both_rgcn_0 -dt test
```

For details, you can refer to ParlAI's documentation here https://parl.ai/

**Comment by ahtsham58** [comment]
Hi,
Thanks for sharing me the command for conversation generation. I executed the command successfully. currently, it uses ReDial test data to pick random conversations and the output looks like this..
![image](https://user-images.githubusercontent.com/23135687/74146585-ada26200-4c01-11ea-9fe1-5245a832b72d.png)

Now I have two questions..
first, the movies name are not mentioned in conversation instead tag ` __unk__]` is used. how can I exactly show movies names in conversation?

secondly, which data file can I use if I want to input my own customized recommendation queries?
i.e.  I want to converse with the system using my own queries, what should i do in that case...

Thanks in advance!

**Comment by qibinc** [comment]
Hi @ahtsham58 ,

Sorry that I provided the wrong command in the last reply. To obtain conversations, you should run `python scripts/display_model.py -t redial -mf saved/transformer_rec_both_rgcn_0 -dt test`.

1. The __unk__ token is used because we want to separate the evaluation of the dialog part and recommender part (in this way the movie names won't affect the dialog quality metrics such as BLEU). To obtain the recommended movies. Please add a line `return Output(list(map(str, return_dict["scores"].argmax(dim=1).tolist())))` at the end of `eval_step` in this file https://github.com/THUDM/KBRD/blob/master/parlai/agents/kbrd/kbrd.py and then run `python scripts/display_model.py -t redial -mf saved/both_rgcn_0 -dt test`.
2. Unfortunately, conversing with the system is beyond the scope of this research paper. This code base is only intended to reproduce the results presented in the paper. My suggestion is that you can look into ParlAI's code for interactively conversing with the system here https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/interactive.py.

Hope this helps!

**Comment by ahtsham58** [comment]
Hi @qibinc ,

Thanks for the detailed answer. I will try soon..

**Comment by ahtsham58** [comment]
Hi @qibinc ,
Thanks for the detailed answer. I did the above and it went well.
Actually, I added one conversation data in the test set make sure the same format as redial dataset with valid movie ids as well.

Right now there is only conversation instance in my test_data.jsonl file.

Ideally it should work, but getting json error like, `KeyError: 'Hey! looking for extremly horrible movie this night'`

could you please tell me what else the reason could be provided that if json is in valid format with exactly same keys and everything? I only changed messages text, but movies ids are same as in dbpedia.

**Comment by qibinc** [comment]
Hi @ahtsham58 ,

Thanks for following up and I'm glad something is working for you!

The KeyError is raised because there isn't this sentence 'Hey! looking for extremly horrible movie this night' in the `text_dict.pkl` file. If you look into this file (e.g., run `d = pkl.load(open('data/redial/text_dict.pkl', 'rb'))`), you will find it's a dict where the keys are sentences and values are extracted entities.

We use this as a cache of extracted entities, as extracting the entity from sentences on the fly causes a bottleneck during training. To solve this, we decided to save the results to `text_dict.pkl`.

Therefore, when adding a new sentence, first we need to extract entities from this sentence, (which maybe `Horror_film` in this case). To do this, you'll need to set up https://github.com/dbpedia-spotlight/spotlight-docker. Then, you can refer to this:

https://github.com/THUDM/KBRD/blob/6cce3976f087ac59325b9c57051489ad488967d2/parlai/tasks/redial/extract_entities.py#L6-L28

Finally, you should add this new entry to `text_dict.pkl` and everything should go well again!

**Comment by ahtsham58** [comment]
ohhhh. I see. 
Really grateful to you. You were so kind in response. Bless you!

**Comment by chrislouis0106** [comment]
> Hi,
> can you please lead how i can generate dialogue conversations using this KBRD system. My model is already trained..

can you tell me how to execute the codes and the process of works；
when I  run the “bash scripts/both.sh 4 4 ”  the mention is no module "parlai"

**Comment by qibinc** [comment]
Hi @Ashappyboy ,

Please add the project path (/xx/xx/KBRD) to your $PYTHONPATH

**Comment by chrislouis0106** [comment]
您好：
谢谢您的回复！
请问项目的两个外部数据文件的目录结构是这样吗，KBRD/data/redial
KBRD/data/dbpedia，dbpedia以解压
祝一起安好！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qibin Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 晚上9:00
收件人:&nbsp;"THUDM/KBRD"<KBRD@noreply.github.com&gt;;
抄送:&nbsp;"朵朵"<884665320@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [THUDM/KBRD] Show_bias.py not executing  (#10)





 
Hi @Ashappyboy ,
 
Please add the project path (/xx/xx/KBRD) to your $PYTHONPATH

**Comment by qibinc** [comment]
Hi @Ashappyboy ,

1. KBRD/data/redial 有一部分是training会自动下载的，然后下载完就把解压好的pkl放进去。
2. dbpedia 请放在 KBRD/dbpedia

很抱歉 README 写的比较粗糙，希望这个回复可以说清楚。

同祝安好~

**Comment by chrislouis0106** [comment]
您好：
谢谢您的回复，我在去努力复现您的项目。
谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qibin Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 晚上9:11
收件人:&nbsp;"THUDM/KBRD"<KBRD@noreply.github.com&gt;;
抄送:&nbsp;"朵朵"<884665320@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [THUDM/KBRD] Show_bias.py not executing  (#10)





 
Hi @Ashappyboy ,
  
KBRD/data/redial 有一部分是training会自动下载的，然后下载完就把解压好的pkl放进去。
 
dbpedia 请放在 KBRD/dbpedia
  
很抱歉 README 写的比较粗糙，希望这个回复可以说清楚。
 
同祝安好~
