### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/KBRD/data/redial/text_dict.pkl'

### ISSUE THREAD

**Issue by luyulalala** [THUDM/KBRD#5]
This problem appeared when I run again.  Hope you can help. Thanks!

**Comment by luyulalala** [comment]
![image](https://user-images.githubusercontent.com/26454989/66703449-5e2c5200-ed45-11e9-8ac4-ad51759aa2a9.png)
I checked your code again, and I still cannot find the entrance for this NotFound  .pkl. Hopes for your reply and thanks again.

**Comment by qibinc** [comment]
Hi @luyulalala ,

Thanks for reminding me of this! Actually this one is particularly troublesome to preprocess as it involves setting up a [dbpedia spotlight docker](https://github.com/dbpedia-spotlight/spotlight-docker). You can see the preprocessing step in `parlai/tasks/redial/extract_entites.py`. It's not called in the main pipeline because of the aforementioned dependency problem.

For the solution, please download it [here](https://cloud.tsinghua.edu.cn/f/88ac4b7eab6c416ca74f/?dl=1) and put it in `/home/KBRD/data/redial/` (preprocessed) so you can skip the docker thing.

Best,

**Comment by luyulalala** [comment]
Thanks a lot!!!!!!!!!!
I worked a night and I nearly want to change the name of your .pkl in this line
![image](https://user-images.githubusercontent.com/26454989/66704492-e531f800-ed4e-11e9-9fa4-f4e254004be9.png)
I am trying now and thanks again!

**Comment by meiyoufeng116** [comment]
The link has expired, could you upload a new one?

**Comment by qibinc** [comment]
Hi @meiyoufeng116 , sorry that I no longer have access to Tsinghua Cloud. However, the Google drive links still work. Please download from a machine which has access to Google and download from those two links. I apologize about the inconvenience.
